name = "edgetunnel-oci-seoul"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"
id = "c6d507e4c11d405793d88d6500b5a76e"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
 --name  --kv-bind "KV="
