name = "edgetunnel-oci-tokyo"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"
id = "a13c4f09cef2462a9df2c104ebc7c7c2"
 
[observability]
[observability.logs]
enabled = false
invocation_logs = true
